apply plugin: 'com.android.application'

android {
    namespace 'org.literacyapp.missing_number'
    compileSdk 36

    defaultConfig {
        applicationId "org.literacyapp.missing_number"
        minSdk 26
        targetSdk 34
        versionCode 1000000
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "CONTENT_PROVIDER_APPLICATION_ID", "\"ai.elimu.content_provider\""
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        encoding = "UTF-8"
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    testImplementation 'junit:junit:4.13.2'
    implementation libs.elimu.content.provider
    implementation libs.elimu.model
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}
